---
- name: Install all security updates
  ansible.builtin.yum:
    security: true
    state: latest
    update_only: true
  register: update_result
  when: ansible_os_family == "RedHat" or ansible_os_famliy == "CentOS"
  become: true
