- name: Install all security updates
  ansible.builtin.shell: grep secu /etc/apt/sources.list > /etc/apt/security.sources.list
  when: ansible_os_family == "Debian"
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when: ansible_os_family == "Debian"
  become: true

- name: Install all updates
  ansible.builtin.apt:
    name: "*"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
