---
- ansible.builtin.include_tasks: windows-patching.yml
  when: ansible_os_family == "Windows"

- ansible.builtin.include_tasks: linux-patching-redhat.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "CentOS"

- ansible.builtin.include_tasks: linux-patching-debian.yml
  when: ansible_os_family == "Debian"
